name: Android CI

on:
  push:
    branches: [ "CI/CD" ]
  pull_request:
    branches: [ "CI/CD" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Install Appium
        run: npm install -g appium

      - name: Start Appium
        run: appium &>/dev/null &
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup Android SDK
        uses: amyu/setup-android@v2
        with:
          sdk-version: '29' # La versión del SDK de Android que deseas instalar

      - name: Run Appium Tests
        uses: reactivecircus/android-emulator-runner@v1 # install and create the Emulator
        with:
          api-level: 30
          target: default
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew test