name: Android CI

on:
  push:
    branches: [ "CI/CD" ]
  pull_request:
    branches: [ "CI/CD" ]

jobs:
  run-mobile-tests:
    runs-on: macos-11


    steps:
      - name: Java
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: pull Project
        uses: actions/checkout@v3

      - name: Setup Appium
        run: |
          npm install -g appium
          appium -v
          appium &>/dev/null &
          
      - name: run appium android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          emulator-build: 9751036
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew :test --tests "co.com.project.automation.prestaApp.runners.Run"