name: Android CI

on:
  push:
    branches: [ "CI/CD" ]
  pull_request:
    branches: [ "CI/CD" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: ./gradlew assemble

      - name: Install Appium
        run: npm install -g appium && appium &

      - name: Set up Android emulator
        uses: android-actions/setup-emulator@v1
        with:
          api-level: 30
          arch: x86_64
          profile: Pixel_3a_API_30

      - name: Start emulator
        uses: android-actions/start-emulator@v1

      - name: Install Xlsx
        run: npm install xlsx


      - name: Run Test
        run: |
          ./gradlew clean
          ./gradlew :test --tests "co.com.project.automation.prestaApp.runners.Run"
