name: Android CI

on:
  push:
    branches: [ "CI/CD" ]
  pull_request:
    branches: [ "CI/CD" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Install Appium Dependencies
        run: |
          sudo npm install -g appium
          sudo npm install -g appium-doctor

      - name: Check Appium Doctor
        run: appium-doctor

      - name: Run Appium Test
        run: ./gradlew clean :test --tests "co.com.project.automation.prestaApp.runners.Run"