name: Android CI

on:
  push:
    branches: [ "CI/CD" ]
  pull_request:
    branches: [ "CI/CD" ]
env:
  PORT: 5554
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: 30
      - name: Install Appium
        run: npm install -g appium

      - name: Start Appium
        run: appium &>/dev/null &

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Appium tests
        run: ./gradlew test