name: Android CI

on:
  push:
    branches: [ "CI/CD" ]
  pull_request:
    branches: [ "CI/CD" ]
env:
  PORT: 5554
jobs:
  run-mobile-tests:
    runs-on: macos-latest

    steps:
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Install nd
        run: npm install -g appium



      - name: pull the project in to the runner
        uses: actions/checkout@v3
      - name: Ejecutar aplicación
        run: npm start --port $PORT
      - name: setup appium
        run: |
          npm install -g appium@v1.22
          appium -v
          appium &>/dev/null &
      - name: run appium android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          script: ./gradlew clean build