name: Android CI

on:
  push:
    branches: [ "master" ]

jobs:
  run-android-test:
    runs-on: macos-latest

    steps:
      - name: set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Driver
        run: npm install appium-uiautomator2-driver
      - name: Setup Appium
        run: |
          npm install -g appium
          appium -v
          appium &>/dev/null &
      - name: Run Test
        run: ./gradlew build
